#pragma once


enum TEXTURE_TYPE
{
	PIKACHU_BLOCK = 0,
	DEWGONG_BLOCK,
	JAMMANBO_BLOCK,
	GGOBUGI_BLOCK,
	PYLEE_BLOCK,

	REMOVE_COLOR_BLOCK,
	REMOVE_ROW_BLOCK,
	REMOVE_COL_BLOCK,
	REMOVE_CROSS_BLOCK,

	PIKACHU_SELECTED,
	DEWGONG_SELECTED,
	JAMMANBO_SELECTED,
	GGOBUGI_SELECTED,
	PYLEE_SELECTED,

	REMOVE_COLOR_BLOCK_SELECTED,
	REMOVE_ROW_BLOCK_SELECTED,
	REMOVE_COL_BLOCK_SELECTED,
	REMOVE_CROSS_BLOCK_SELECTED,

	WALL,
	USABLE_WALL,
	ICE_WALL,
	EMPTY_BTN,
	WALLTYPE_END,

	BACKGROUND,
	SCOREBOARD,
	PLAY_BUTTON,
	EMPTY_BUTTON,
	STAGE_1_BUTTON,
	STAGE_1_BUTTON_X,
	STAGE_2_BUTTON,
	STAGE_2_BUTTON_X,
	STAGE_3_BUTTON,
	STAGE_3_BUTTON_X,

	LOCK_BUTTON,

	BOARD_5X5,

	BOOM_0,
	BOOM_1,
	BOOM_2,
	BOOM_3,
	BOOM_END,

	SAVE_BTN,
	MAPTOOL_BTN,
};

class Texture;
class ResourceManager
{
	SINGLETON(ResourceManager)
private:
	std::map<std::string, Texture*> m_MapTexture;
	std::string GetTextureFileName(TEXTURE_TYPE _eTextureType, DIRECTION _eDirection);
	
public:
	Texture* LoadTexture(TEXTURE_TYPE _eTextureType, DIRECTION _eDirection = DIRECTION::END);
	Texture* FindTexture(const std::string& _strKey);

};

